version: 0.2
phases:
  pre_build:
    commands:
      - start-dockerd
      - pyenv global 3.12.2 3.10.13
      - cd sagemaker-mlops
      - pip3.10 install -U boto3 awscli requests tox==3.28.0 twine fabric tox-pip-version
      - pip3.12 install -U boto3 awscli requests tox==3.28.0 twine fabric tox-pip-version
  build:
    commands:
      - IGNORE_COVERAGE=-
      - echo "=== py312 spark_py312 tests ==="
      - tox -e py312 -- tests/integ -v -m spark_py312 --durations 50
